### PR TITLE
Revert to old `Fr::ZETA`

### PR DESCRIPTION
**Pull request by kilic**
Rebase of #33 with required changes. Additionally grumpkin scalars decomposition is added.

### CODE REVIEW

**Review by CPerezz — APPROVED** [review]
LGTM!

**Comment by CPerezz** [comment]
@kilic I approved as the params were correct. But can you first fix the clippy/asm errs?

**Comment by chokobole** [comment]
@CPerezz I have a question! 

In order to satisfy `ZETA^3 = 1 mod r where ZETA^2 != 1 mod r`, shouldn't `Zeta`  be calculated in this way ?

$\zeta=g^{\frac{2^s \times T}{3}}$

Then I think the previous one is right one, If i'm wrong, please let me know!

**Comment by CPerezz** [comment]
Hey @chokobole 

I think I ran Sage to check the params. Have you run it and find out that it doesn't work. 
This would be weird as the pairing works correctly in all the dependant-libs.

You basically need to pick a Z such that you end up in a multiplicative sub-group of order 3. But will double check in case the current param is wrong. 

I'm on leave but can run it next week. Otherwise, can you provide your Sage results to compare and work from there?

**Comment by chokobole** [comment]
Hi @CPerezz, I actually didn't run Sage, rather I had a code in c++. I though the `Z` that we need is a value, multiplicative sub-group of order 3 and the suggested one above is more simple way to find this value, but PSE Halo2 Curve uses a value by squaring it.

https://github.com/kroma-network/tachyon/blob/08f6253b33ca32ab0b46bd5067ba0be421a30561/tachyon/zk/plonk/vanishing/vanishing_utils.h#L22-L45

```c++
// Calculate ζ = g^((2ˢ * T) / 3).
template <typename F>
constexpr F GetZeta() {
  using BigInt = typename F::BigIntTy;
  CHECK_EQ(F::Config::kTrace % BigInt(3), BigInt(0));
  BigInt exp = F::Config::kTrace;
  // NOTE(chokobole): The result of the exponential operation does not exceed
  // the modulus of the scalar field.
  exp.MulBy2ExpInPlace(F::Config::kTwoAdicity);
  exp /= BigInt(3);
  return F::FromMontgomery(F::Config::kSubgroupGenerator).Pow(exp);
}

// NOTE(TomTaehoonKim): The returning value of |GetZeta()| is different from the
// one in
// https://github.com/kroma-network/halo2curves/blob/c0ac1935e5da2a620204b5b011be2c924b1e0155/src/bn256/fr.rs#L112-L118.
// This is an ugly way to produce a same result with Halo2Curves but we will
// remove once we don't have to match it against Halo2 any longer in the
// future.
// Calculate ζ = g^((2ˢ * T) / 3)².
template <typename F>
constexpr F GetHalo2Zeta() {
  return GetZeta<F>().Square();
}
```

**Pull request merged**
