### PR TITLE
[feat] implement MaybeU64 for BN254::ScalarField

### PR DESCRIPTION
**Pull request by zhenfeizhang**
This PR implements the `MaybeU64` struct for `BN256::ScalarField`.
When we need to perform arithmetic over the scalar field of small elements that are less then 64 bits, we store the result in u64 rather than a whole field element.
It is useful when dealing with something like keccak circuit where most of the witnesses are less than 24 bits.

__limitations__
- If the inputs are not sparse then there is a 10%ish penalty due to the wrapper.
- Some of the constant time traits are no longer constant time.

In principle we can also implement this for other field. But this only appears useful for witness generation and thus BN256::ScalarField.

```
cargo test --release bench_maybe_u64  --features=print-trace,bn256-table,maybe_u64 -- --nocapture
```

```
Start:   Native Fr with 32 bits 10000 muls with initialization
End:     Native Fr with 32 bits 10000 muls with initialization .....................1.825ms
Start:   maybe64 Fr with 32 bits 10000 muls with initialization
End:     maybe64 Fr with 32 bits 10000 muls with initialization ....................521.441µs
Start:   Native Fr with 64 bits 10000 muls with initialization
End:     Native Fr with 64 bits 10000 muls with initialization .....................1.765ms
Start:   maybe64 Fr with 64 bits 10000 muls with initialization
End:     maybe64 Fr with 64 bits 10000 muls with initialization ....................1.379ms
Start:   Native Fr with 256 bits 10000 muls without initialization
End:     Native Fr with 256 bits 10000 muls without initialization .................339.301µs
Start:   maybe64 Fr with 256 bits 10000 muls without initialization
End:     maybe64 Fr with 256 bits 10000 muls without initialization ................378.221µs
```

### CODE REVIEW

**Comment by kilic** [comment]
It is a nice trick to reduce amount of work for small elements. However it feels like very application specific feature in exchange for relatively huge diff. What do you think if such use case could be sorted out at circuit development side? @zhenfeizhang @han0110

**Comment by CPerezz** [comment]
I'm not sure how the circuit specific relates to this PR. This would make significantly faster MSM's (in case scalars are U64-fit). And would speed up in general any operation with small scalars.

But as for what circuit refers, this makes no difference at all. There was a really interesting conversation in the ZKStudy TG group this week anyways about that specifically. 
Seems that using GLV to half the bits + have `ShortScalar` for 128 or even less bits and doing only addition and no doubling are the best solutions out there.

Highly suggest to take a look to it! @kilic

**Comment by kilic** [comment]
We already have the speed up effect of short scalars in double-add rounds. We decompose scalars in some base B digitsand  If a digit is zero we just send the corresponding point to the null bucket which has no effect in further calculation. Discussion in the TG group was mostly about in circuit ecc multiplication and scalar witnesses there can even be represented as Value<usize> or smtg similar before assignments

**Comment by CPerezz** [comment]
Ohh now I understand the "circuit development side" thing that you said. I misunderstood you!
It's quite contained in here IMO. But agree that this is a big diff. Not sure how much more code will require to extend the feature to all the other fields.

**Comment by zhenfeizhang** [comment]
> What do you think if such use case could be sorted out at circuit development side?

not sure how this would be sorted out at application easily.
I was planning to hide `MaybeU64` under a feature flag and will not be invoked in most cases except for applications that are relevant. (I accidentally added it to default -- i should revert it)

>  they can even be represented as Value<usize>

I __think__, without looking much into details, this is a more complicate than this PR. It requires changes in `halo2proof` (for example, implement `Field` for `Value<usize/u64>`(?)) and also incurs an breaking change in `Value` APIs so the circuit implementation will likely need an update as well.

This PR is fully compatible with down streams.

> Not sure how much more code will require to extend the feature to all the other fields.

1. I don't think base fields need this. But yes it would be nice to enable it for curves like Pasta (if they are used in production and witness gen is also a bottleneck their)
2. If we were to do it I guess it would be too much complicated than something along the line

```
type Fr = MaybeU64<pallas::Fr>
```

**Comment by zhenfeizhang** [comment]
> We already have the speed up effect of short scalars in double-add rounds. We decompose scalars in some base B digitsand If a digit is zero we just send the corresponding point to the null bucket which has no effect in further calculation.

the new struct is not really used to accelerate scalar mul.

the main usage is during witness gen where we actually do a lot arithmetic over the field element before actually commit to it (doing Group mul)

**Comment by han0110** [comment]
> This PR is fully compatible with down streams.

The `maybe_u64` module looks great to me, curious if it's possible for downstream user to just declare a alias `type Fr = MaybeU64<bn256::Fr>` when necessary, and we can keep `bn256::Fr` and `grumpkin::Fr` unchanged, I think this might be a cleaner approach?

The only difference I see for the wrapper is the `bn256::Fr::from_raw` now understands `u64`, but actually we could also use `F::from(xxx_u64)` to initialize a `MaybeU64::U64` right?

Also if the only goal is to have less field operations on witness generation, I think we can have a wrapper struct like struct `U64(u64)` and implement `From<&U64> for Assigned<F>` for it, just like how `sha256::Bits` works https://github.com/privacy-scaling-explorations/halo2/blob/818febb61da16c76e43469f626e87d01e98db309/halo2_gadgets/src/sha256/table16.rs#L84-L89.

Then the `AssignedCell` now only holds `Value<U64>`.

**Comment by zhenfeizhang** [comment]
> The maybe_u64 module looks great to me, curious if it's possible for downstream user to just declare an alias type Fr = MaybeU64<bn256::Fr> when necessary, and we can keep bn256::Fr and grumpkin::Fr unchanged, I think this might be a cleaner approach?

I like this approach. So I guess the resolution is to close this PR and leave MaybeU64 as a separate crate that the down stream can optionally import?

**Comment by han0110** [comment]
> So I guess the resolution is to close this PR and leave MaybeU64 as a separate crate that the down stream can optionally import?

Yeah that might be an easier approach considering it might need more customized features than `halo2curves` itself. But if upstreaming it here really helps composability I think it's also okay to have the `maybe_u64` module merged.

**Comment by zhenfeizhang** [comment]
Sounds good. Thanks for the discussion. Closing now.

**Pull request closed without merging**
